name = "VÃµro"
version = "0.1.1"

[macos]
system_pkg_id = "no.divvun.MacDivvun.vro"

[windows]
system_product_code = "3F977B67-7BAE-4772-A64B-5B16BFDAEBA8"
msoffice_product_code = "44D38263-914F-4410-B3D2-1D5EDDEDA5EC"
