# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Võro spellchecker"
vro = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Võro, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
vro = "TRANSLATE: A spellchecker for Võro, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.vro"

[windows]
system_product_code = "{784B0AA1-625D-4C59-8F18-1CB200D894C7}_is1"
legacy_product_codes = [
    { value = "3F977B67-7BAE-4772-A64B-5B16BFDAEBA8", kind = "nsis" },
    { value = "44D38263-914F-4410-B3D2-1D5EDDEDA5EC", kind = "nsis" }
]

[package.speller]
name = "Võro"
version = "0.1.1-rc1"

[package.grammar]
name = "Võro"
version = "0.1.0"

[package.tts-text-proc]
name = "Võro"
version = "0.1.0"
