template = "https://github.com/giellalt/template-lang-und"
rev_id = 225
template_sha = "f41519ddc2fe90fa957f23f2acb5b371f70bf4e4"

[replacements]
__REPO__ = "lang-vro"
__UND2C__ = "vro"
__UNDEFINED__ = "VÃµro"
__UND__ = "vro"
