template = "https://github.com/giellalt/template-lang-und"
rev_id = 232
template_sha = "c0fbeeb0092350cd80544dae78d27a643094d3ea"

[replacements]
__REPO__ = "lang-vro"
__UND2C__ = "vro"
__UNDEFINED__ = "VÃµro"
__UND__ = "vro"
