template = "https://github.com/giellalt/template-lang-und"
rev_id = 262
template_sha = "e76bfc45ca43118d648ca429564512658ac2ea78"

[replacements]
__GLOTTOLOG_ID__ = "sout2679"
__REPO__ = "lang-vro"
__UND2C__ = "vro"
__UNDEFINED__ = "VÃµro"
__UND__ = "vro"
