template = "https://github.com/giellalt/template-lang-und"
rev_id = 165
template_sha = "e90d50ced16049c0fd339de88458c3e44708f347"

[replacements]
__REPO__ = "lang-vro"
__UND2C__ = "vro"
__UNDEFINED__ = "VÃµro"
__UND__ = "vro"
